title: projets.pl
email: studio@projets.pl
description: Spraw, aby Twoja firma postrzegana była jako innowacyjna. Postaw na profesjonalną stronę www, dedykowaną aplikację internetową i zbuduj pozycję swojej marki.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://millto.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: projetspl
github_username:  projetspl
lang: "pl"

markdown: kramdown

remote_theme: arturmatlega/ig-theme

toc:
  min_level: 2
  max_level: 2

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-remote-theme

ampdir: amp

collections:
  posts:    
    permalink: /blog/:title:output_ext